{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='pushSecret', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of PushSecret', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'external-secrets.io/v1alpha1',
    kind: 'PushSecret',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"PushSecretSpec configures the behavior of the PushSecret."'),
  spec: {
    '#data':: d.obj(help='"Secret Data that should be pushed to providers"'),
    data: {
      '#match':: d.obj(help='"Match a given Secret Key to be pushed to the provider."'),
      match: {
        '#remoteRef':: d.obj(help='"Remote Refs to push to providers."'),
        remoteRef: {
          '#withProperty':: d.fn(help='"Name of the property in the resulting secret"', args=[d.arg(name='property', type=d.T.string)]),
          withProperty(property): { match+: { remoteRef+: { property: property } } },
          '#withRemoteKey':: d.fn(help='"Name of the resulting provider secret."', args=[d.arg(name='remoteKey', type=d.T.string)]),
          withRemoteKey(remoteKey): { match+: { remoteRef+: { remoteKey: remoteKey } } },
        },
        '#withSecretKey':: d.fn(help='"Secret Key to be pushed"', args=[d.arg(name='secretKey', type=d.T.string)]),
        withSecretKey(secretKey): { match+: { secretKey: secretKey } },
      },
      '#withConversionStrategy':: d.fn(help='"Used to define a conversion Strategy for the secret keys"', args=[d.arg(name='conversionStrategy', type=d.T.string)]),
      withConversionStrategy(conversionStrategy): { conversionStrategy: conversionStrategy },
      '#withMetadata':: d.fn(help='"Metadata is metadata attached to the secret.\\nThe structure of metadata is provider specific, please look it up in the provider documentation."', args=[d.arg(name='metadata', type=d.T.any)]),
      withMetadata(metadata): { metadata: metadata },
    },
    '#secretStoreRefs':: d.obj(help=''),
    secretStoreRefs: {
      '#labelSelector':: d.obj(help='"Optionally, sync to secret stores with label selector"'),
      labelSelector: {
        '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
        matchExpressions: {
          '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
          withOperator(operator): { operator: operator },
          '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
          withValues(values): { values: if std.isArray(v=values) then values else [values] },
          '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
          withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
        },
        '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressions(matchExpressions): { labelSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } },
        '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressionsMixin(matchExpressions): { labelSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } },
        '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { labelSelector+: { matchLabels: matchLabels } },
        '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { labelSelector+: { matchLabels+: matchLabels } },
      },
      '#withKind':: d.fn(help='"Kind of the SecretStore resource (SecretStore or ClusterSecretStore)"', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withName':: d.fn(help='"Optionally, sync to the SecretStore of the given name"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
    },
    '#selector':: d.obj(help='"The Secret Selector (k8s source) for the Push Secret"'),
    selector: {
      '#generatorRef':: d.obj(help='"Point to a generator to create a Secret."'),
      generatorRef: {
        '#withApiVersion':: d.fn(help='"Specify the apiVersion of the generator resource"', args=[d.arg(name='apiVersion', type=d.T.string)]),
        withApiVersion(apiVersion): { spec+: { selector+: { generatorRef+: { apiVersion: apiVersion } } } },
        '#withKind':: d.fn(help='"Specify the Kind of the generator resource"', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { spec+: { selector+: { generatorRef+: { kind: kind } } } },
        '#withName':: d.fn(help='"Specify the name of the generator resource"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { selector+: { generatorRef+: { name: name } } } },
      },
      '#secret':: d.obj(help='"Select a Secret to Push."'),
      secret: {
        '#selector':: d.obj(help='"Selector chooses secrets using a labelSelector."'),
        selector: {
          '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
          matchExpressions: {
            '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
            withOperator(operator): { operator: operator },
            '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
            withValues(values): { values: if std.isArray(v=values) then values else [values] },
            '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
            withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
          },
          '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressions(matchExpressions): { spec+: { selector+: { secret+: { selector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } } },
          '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressionsMixin(matchExpressions): { spec+: { selector+: { secret+: { selector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } } },
          '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { spec+: { selector+: { secret+: { selector+: { matchLabels: matchLabels } } } } },
          '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { spec+: { selector+: { secret+: { selector+: { matchLabels+: matchLabels } } } } },
        },
        '#withName':: d.fn(help='"Name of the Secret.\\nThe Secret must exist in the same namespace as the PushSecret manifest."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { selector+: { secret+: { name: name } } } },
      },
    },
    '#template':: d.obj(help='"Template defines a blueprint for the created Secret resource."'),
    template: {
      '#metadata':: d.obj(help='"ExternalSecretTemplateMetadata defines metadata fields for the Secret blueprint."'),
      metadata: {
        '#withAnnotations':: d.fn(help='', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { template+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { template+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { template+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { template+: { metadata+: { labels+: labels } } } },
      },
      '#templateFrom':: d.obj(help=''),
      templateFrom: {
        '#configMap':: d.obj(help=''),
        configMap: {
          '#items':: d.obj(help='"A list of keys in the ConfigMap/Secret to use as templates for Secret data"'),
          items: {
            '#withKey':: d.fn(help='"A key in the ConfigMap/Secret"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withTemplateAs':: d.fn(help='', args=[d.arg(name='templateAs', type=d.T.string)]),
            withTemplateAs(templateAs): { templateAs: templateAs },
          },
          '#withItems':: d.fn(help='"A list of keys in the ConfigMap/Secret to use as templates for Secret data"', args=[d.arg(name='items', type=d.T.array)]),
          withItems(items): { configMap+: { items: if std.isArray(v=items) then items else [items] } },
          '#withItemsMixin':: d.fn(help='"A list of keys in the ConfigMap/Secret to use as templates for Secret data"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='items', type=d.T.array)]),
          withItemsMixin(items): { configMap+: { items+: if std.isArray(v=items) then items else [items] } },
          '#withName':: d.fn(help='"The name of the ConfigMap/Secret resource"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { configMap+: { name: name } },
        },
        '#secret':: d.obj(help=''),
        secret: {
          '#items':: d.obj(help='"A list of keys in the ConfigMap/Secret to use as templates for Secret data"'),
          items: {
            '#withKey':: d.fn(help='"A key in the ConfigMap/Secret"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withTemplateAs':: d.fn(help='', args=[d.arg(name='templateAs', type=d.T.string)]),
            withTemplateAs(templateAs): { templateAs: templateAs },
          },
          '#withItems':: d.fn(help='"A list of keys in the ConfigMap/Secret to use as templates for Secret data"', args=[d.arg(name='items', type=d.T.array)]),
          withItems(items): { secret+: { items: if std.isArray(v=items) then items else [items] } },
          '#withItemsMixin':: d.fn(help='"A list of keys in the ConfigMap/Secret to use as templates for Secret data"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='items', type=d.T.array)]),
          withItemsMixin(items): { secret+: { items+: if std.isArray(v=items) then items else [items] } },
          '#withName':: d.fn(help='"The name of the ConfigMap/Secret resource"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { secret+: { name: name } },
        },
        '#withLiteral':: d.fn(help='', args=[d.arg(name='literal', type=d.T.string)]),
        withLiteral(literal): { literal: literal },
        '#withTarget':: d.fn(help='', args=[d.arg(name='target', type=d.T.string)]),
        withTarget(target): { target: target },
      },
      '#withData':: d.fn(help='', args=[d.arg(name='data', type=d.T.object)]),
      withData(data): { spec+: { template+: { data: data } } },
      '#withDataMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='data', type=d.T.object)]),
      withDataMixin(data): { spec+: { template+: { data+: data } } },
      '#withEngineVersion':: d.fn(help='"EngineVersion specifies the template engine version\\nthat should be used to compile/execute the\\ntemplate specified in .data and .templateFrom[]."', args=[d.arg(name='engineVersion', type=d.T.string)]),
      withEngineVersion(engineVersion): { spec+: { template+: { engineVersion: engineVersion } } },
      '#withMergePolicy':: d.fn(help='', args=[d.arg(name='mergePolicy', type=d.T.string)]),
      withMergePolicy(mergePolicy): { spec+: { template+: { mergePolicy: mergePolicy } } },
      '#withTemplateFrom':: d.fn(help='', args=[d.arg(name='templateFrom', type=d.T.array)]),
      withTemplateFrom(templateFrom): { spec+: { template+: { templateFrom: if std.isArray(v=templateFrom) then templateFrom else [templateFrom] } } },
      '#withTemplateFromMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='templateFrom', type=d.T.array)]),
      withTemplateFromMixin(templateFrom): { spec+: { template+: { templateFrom+: if std.isArray(v=templateFrom) then templateFrom else [templateFrom] } } },
      '#withType':: d.fn(help='', args=[d.arg(name='type', type=d.T.string)]),
      withType(type): { spec+: { template+: { type: type } } },
    },
    '#withData':: d.fn(help='"Secret Data that should be pushed to providers"', args=[d.arg(name='data', type=d.T.array)]),
    withData(data): { spec+: { data: if std.isArray(v=data) then data else [data] } },
    '#withDataMixin':: d.fn(help='"Secret Data that should be pushed to providers"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='data', type=d.T.array)]),
    withDataMixin(data): { spec+: { data+: if std.isArray(v=data) then data else [data] } },
    '#withDeletionPolicy':: d.fn(help='"Deletion Policy to handle Secrets in the provider."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withRefreshInterval':: d.fn(help='"The Interval to which External Secrets will try to push a secret definition"', args=[d.arg(name='refreshInterval', type=d.T.string)]),
    withRefreshInterval(refreshInterval): { spec+: { refreshInterval: refreshInterval } },
    '#withSecretStoreRefs':: d.fn(help='', args=[d.arg(name='secretStoreRefs', type=d.T.array)]),
    withSecretStoreRefs(secretStoreRefs): { spec+: { secretStoreRefs: if std.isArray(v=secretStoreRefs) then secretStoreRefs else [secretStoreRefs] } },
    '#withSecretStoreRefsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='secretStoreRefs', type=d.T.array)]),
    withSecretStoreRefsMixin(secretStoreRefs): { spec+: { secretStoreRefs+: if std.isArray(v=secretStoreRefs) then secretStoreRefs else [secretStoreRefs] } },
    '#withUpdatePolicy':: d.fn(help='"UpdatePolicy to handle Secrets in the provider."', args=[d.arg(name='updatePolicy', type=d.T.string)]),
    withUpdatePolicy(updatePolicy): { spec+: { updatePolicy: updatePolicy } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
