{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='vaultDynamicSecret', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of VaultDynamicSecret', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'generators.external-secrets.io/v1alpha1',
    kind: 'VaultDynamicSecret',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#provider':: d.obj(help='"Vault provider common spec"'),
    provider: {
      '#auth':: d.obj(help='"Auth configures how secret-manager authenticates with the Vault server."'),
      auth: {
        '#appRole':: d.obj(help='"AppRole authenticates with Vault using the App Role auth mechanism,\\nwith the role and secret stored in a Kubernetes Secret resource."'),
        appRole: {
          '#roleRef':: d.obj(help='"Reference to a key in a Secret that contains the App Role ID used\\nto authenticate with Vault.\\nThe `key` field must be specified and denotes which entry within the Secret\\nresource is used as the app role id."'),
          roleRef: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { appRole+: { roleRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { appRole+: { roleRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { appRole+: { roleRef+: { namespace: namespace } } } } } },
          },
          '#secretRef':: d.obj(help='"Reference to a key in a Secret that contains the App Role secret used\\nto authenticate with Vault.\\nThe `key` field must be specified and denotes which entry within the Secret\\nresource is used as the app role secret."'),
          secretRef: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { appRole+: { secretRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { appRole+: { secretRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { appRole+: { secretRef+: { namespace: namespace } } } } } },
          },
          '#withPath':: d.fn(help='"Path where the App Role authentication backend is mounted\\nin Vault, e.g: \\"approle\\', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { spec+: { provider+: { auth+: { appRole+: { path: path } } } } },
          '#withRoleId':: d.fn(help='"RoleID configured in the App Role authentication backend when setting\\nup the authentication backend in Vault."', args=[d.arg(name='roleId', type=d.T.string)]),
          withRoleId(roleId): { spec+: { provider+: { auth+: { appRole+: { roleId: roleId } } } } },
        },
        '#cert':: d.obj(help='"Cert authenticates with TLS Certificates by passing client certificate, private key and ca certificate\\nCert authentication method"'),
        cert: {
          '#clientCert':: d.obj(help='"ClientCert is a certificate to authenticate using the Cert Vault\\nauthentication method"'),
          clientCert: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { cert+: { clientCert+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { cert+: { clientCert+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { cert+: { clientCert+: { namespace: namespace } } } } } },
          },
          '#secretRef':: d.obj(help='"SecretRef to a key in a Secret resource containing client private key to\\nauthenticate with Vault using the Cert authentication method"'),
          secretRef: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { cert+: { secretRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { cert+: { secretRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { cert+: { secretRef+: { namespace: namespace } } } } } },
          },
        },
        '#iam':: d.obj(help='"Iam authenticates with vault by passing a special AWS request signed with AWS IAM credentials\\nAWS IAM authentication method"'),
        iam: {
          '#jwt':: d.obj(help='"Specify a service account with IRSA enabled"'),
          jwt: {
            '#serviceAccountRef':: d.obj(help='"A reference to a ServiceAccount resource."'),
            serviceAccountRef: {
              '#withAudiences':: d.fn(help='"Audience specifies the `aud` claim for the service account token\\nIf the service account uses a well-known annotation for e.g. IRSA or GCP Workload Identity\\nthen this audiences will be appended to the list"', args=[d.arg(name='audiences', type=d.T.array)]),
              withAudiences(audiences): { spec+: { provider+: { auth+: { iam+: { jwt+: { serviceAccountRef+: { audiences: if std.isArray(v=audiences) then audiences else [audiences] } } } } } } },
              '#withAudiencesMixin':: d.fn(help='"Audience specifies the `aud` claim for the service account token\\nIf the service account uses a well-known annotation for e.g. IRSA or GCP Workload Identity\\nthen this audiences will be appended to the list"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='audiences', type=d.T.array)]),
              withAudiencesMixin(audiences): { spec+: { provider+: { auth+: { iam+: { jwt+: { serviceAccountRef+: { audiences+: if std.isArray(v=audiences) then audiences else [audiences] } } } } } } },
              '#withName':: d.fn(help='"The name of the ServiceAccount resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { provider+: { auth+: { iam+: { jwt+: { serviceAccountRef+: { name: name } } } } } } },
              '#withNamespace':: d.fn(help='"Namespace of the resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { spec+: { provider+: { auth+: { iam+: { jwt+: { serviceAccountRef+: { namespace: namespace } } } } } } },
            },
          },
          '#secretRef':: d.obj(help='"Specify credentials in a Secret object"'),
          secretRef: {
            '#accessKeyIDSecretRef':: d.obj(help='"The AccessKeyID is used for authentication"'),
            accessKeyIDSecretRef: {
              '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { spec+: { provider+: { auth+: { iam+: { secretRef+: { accessKeyIDSecretRef+: { key: key } } } } } } },
              '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { provider+: { auth+: { iam+: { secretRef+: { accessKeyIDSecretRef+: { name: name } } } } } } },
              '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { spec+: { provider+: { auth+: { iam+: { secretRef+: { accessKeyIDSecretRef+: { namespace: namespace } } } } } } },
            },
            '#secretAccessKeySecretRef':: d.obj(help='"The SecretAccessKey is used for authentication"'),
            secretAccessKeySecretRef: {
              '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { spec+: { provider+: { auth+: { iam+: { secretRef+: { secretAccessKeySecretRef+: { key: key } } } } } } },
              '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { provider+: { auth+: { iam+: { secretRef+: { secretAccessKeySecretRef+: { name: name } } } } } } },
              '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { spec+: { provider+: { auth+: { iam+: { secretRef+: { secretAccessKeySecretRef+: { namespace: namespace } } } } } } },
            },
            '#sessionTokenSecretRef':: d.obj(help='"The SessionToken used for authentication\\nThis must be defined if AccessKeyID and SecretAccessKey are temporary credentials\\nsee: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html"'),
            sessionTokenSecretRef: {
              '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { spec+: { provider+: { auth+: { iam+: { secretRef+: { sessionTokenSecretRef+: { key: key } } } } } } },
              '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { provider+: { auth+: { iam+: { secretRef+: { sessionTokenSecretRef+: { name: name } } } } } } },
              '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { spec+: { provider+: { auth+: { iam+: { secretRef+: { sessionTokenSecretRef+: { namespace: namespace } } } } } } },
            },
          },
          '#withExternalID':: d.fn(help='"AWS External ID set on assumed IAM roles"', args=[d.arg(name='externalID', type=d.T.string)]),
          withExternalID(externalID): { spec+: { provider+: { auth+: { iam+: { externalID: externalID } } } } },
          '#withPath':: d.fn(help='"Path where the AWS auth method is enabled in Vault, e.g: \\"aws\\', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { spec+: { provider+: { auth+: { iam+: { path: path } } } } },
          '#withRegion':: d.fn(help='"AWS region"', args=[d.arg(name='region', type=d.T.string)]),
          withRegion(region): { spec+: { provider+: { auth+: { iam+: { region: region } } } } },
          '#withRole':: d.fn(help='"This is the AWS role to be assumed before talking to vault"', args=[d.arg(name='role', type=d.T.string)]),
          withRole(role): { spec+: { provider+: { auth+: { iam+: { role: role } } } } },
          '#withVaultAwsIamServerID':: d.fn(help='"X-Vault-AWS-IAM-Server-ID is an additional header used by Vault IAM auth method to mitigate against different types of replay attacks. More details here: https://developer.hashicorp.com/vault/docs/auth/aws"', args=[d.arg(name='vaultAwsIamServerID', type=d.T.string)]),
          withVaultAwsIamServerID(vaultAwsIamServerID): { spec+: { provider+: { auth+: { iam+: { vaultAwsIamServerID: vaultAwsIamServerID } } } } },
          '#withVaultRole':: d.fn(help='"Vault Role. In vault, a role describes an identity with a set of permissions, groups, or policies you want to attach a user of the secrets engine"', args=[d.arg(name='vaultRole', type=d.T.string)]),
          withVaultRole(vaultRole): { spec+: { provider+: { auth+: { iam+: { vaultRole: vaultRole } } } } },
        },
        '#jwt':: d.obj(help='"Jwt authenticates with Vault by passing role and JWT token using the\\nJWT/OIDC authentication method"'),
        jwt: {
          '#kubernetesServiceAccountToken':: d.obj(help='"Optional ServiceAccountToken specifies the Kubernetes service account for which to request\\na token for with the `TokenRequest` API."'),
          kubernetesServiceAccountToken: {
            '#serviceAccountRef':: d.obj(help='"Service account field containing the name of a kubernetes ServiceAccount."'),
            serviceAccountRef: {
              '#withAudiences':: d.fn(help='"Audience specifies the `aud` claim for the service account token\\nIf the service account uses a well-known annotation for e.g. IRSA or GCP Workload Identity\\nthen this audiences will be appended to the list"', args=[d.arg(name='audiences', type=d.T.array)]),
              withAudiences(audiences): { spec+: { provider+: { auth+: { jwt+: { kubernetesServiceAccountToken+: { serviceAccountRef+: { audiences: if std.isArray(v=audiences) then audiences else [audiences] } } } } } } },
              '#withAudiencesMixin':: d.fn(help='"Audience specifies the `aud` claim for the service account token\\nIf the service account uses a well-known annotation for e.g. IRSA or GCP Workload Identity\\nthen this audiences will be appended to the list"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='audiences', type=d.T.array)]),
              withAudiencesMixin(audiences): { spec+: { provider+: { auth+: { jwt+: { kubernetesServiceAccountToken+: { serviceAccountRef+: { audiences+: if std.isArray(v=audiences) then audiences else [audiences] } } } } } } },
              '#withName':: d.fn(help='"The name of the ServiceAccount resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { provider+: { auth+: { jwt+: { kubernetesServiceAccountToken+: { serviceAccountRef+: { name: name } } } } } } },
              '#withNamespace':: d.fn(help='"Namespace of the resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { spec+: { provider+: { auth+: { jwt+: { kubernetesServiceAccountToken+: { serviceAccountRef+: { namespace: namespace } } } } } } },
            },
            '#withAudiences':: d.fn(help='"Optional audiences field that will be used to request a temporary Kubernetes service\\naccount token for the service account referenced by `serviceAccountRef`.\\nDefaults to a single audience `vault` it not specified.\\nDeprecated: use serviceAccountRef.Audiences instead"', args=[d.arg(name='audiences', type=d.T.array)]),
            withAudiences(audiences): { spec+: { provider+: { auth+: { jwt+: { kubernetesServiceAccountToken+: { audiences: if std.isArray(v=audiences) then audiences else [audiences] } } } } } },
            '#withAudiencesMixin':: d.fn(help='"Optional audiences field that will be used to request a temporary Kubernetes service\\naccount token for the service account referenced by `serviceAccountRef`.\\nDefaults to a single audience `vault` it not specified.\\nDeprecated: use serviceAccountRef.Audiences instead"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='audiences', type=d.T.array)]),
            withAudiencesMixin(audiences): { spec+: { provider+: { auth+: { jwt+: { kubernetesServiceAccountToken+: { audiences+: if std.isArray(v=audiences) then audiences else [audiences] } } } } } },
            '#withExpirationSeconds':: d.fn(help='"Optional expiration time in seconds that will be used to request a temporary\\nKubernetes service account token for the service account referenced by\\n`serviceAccountRef`.\\nDeprecated: this will be removed in the future.\\nDefaults to 10 minutes."', args=[d.arg(name='expirationSeconds', type=d.T.integer)]),
            withExpirationSeconds(expirationSeconds): { spec+: { provider+: { auth+: { jwt+: { kubernetesServiceAccountToken+: { expirationSeconds: expirationSeconds } } } } } },
          },
          '#secretRef':: d.obj(help='"Optional SecretRef that refers to a key in a Secret resource containing JWT token to\\nauthenticate with Vault using the JWT/OIDC authentication method."'),
          secretRef: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { jwt+: { secretRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { jwt+: { secretRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { jwt+: { secretRef+: { namespace: namespace } } } } } },
          },
          '#withPath':: d.fn(help='"Path where the JWT authentication backend is mounted\\nin Vault, e.g: \\"jwt\\', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { spec+: { provider+: { auth+: { jwt+: { path: path } } } } },
          '#withRole':: d.fn(help='"Role is a JWT role to authenticate using the JWT/OIDC Vault\\nauthentication method"', args=[d.arg(name='role', type=d.T.string)]),
          withRole(role): { spec+: { provider+: { auth+: { jwt+: { role: role } } } } },
        },
        '#kubernetes':: d.obj(help='"Kubernetes authenticates with Vault by passing the ServiceAccount\\ntoken stored in the named Secret resource to the Vault server."'),
        kubernetes: {
          '#secretRef':: d.obj(help='"Optional secret field containing a Kubernetes ServiceAccount JWT used\\nfor authenticating with Vault. If a name is specified without a key,\\n`token` is the default. If one is not specified, the one bound to\\nthe controller will be used."'),
          secretRef: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { kubernetes+: { secretRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { kubernetes+: { secretRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { kubernetes+: { secretRef+: { namespace: namespace } } } } } },
          },
          '#serviceAccountRef':: d.obj(help='"Optional service account field containing the name of a kubernetes ServiceAccount.\\nIf the service account is specified, the service account secret token JWT will be used\\nfor authenticating with Vault. If the service account selector is not supplied,\\nthe secretRef will be used instead."'),
          serviceAccountRef: {
            '#withAudiences':: d.fn(help='"Audience specifies the `aud` claim for the service account token\\nIf the service account uses a well-known annotation for e.g. IRSA or GCP Workload Identity\\nthen this audiences will be appended to the list"', args=[d.arg(name='audiences', type=d.T.array)]),
            withAudiences(audiences): { spec+: { provider+: { auth+: { kubernetes+: { serviceAccountRef+: { audiences: if std.isArray(v=audiences) then audiences else [audiences] } } } } } },
            '#withAudiencesMixin':: d.fn(help='"Audience specifies the `aud` claim for the service account token\\nIf the service account uses a well-known annotation for e.g. IRSA or GCP Workload Identity\\nthen this audiences will be appended to the list"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='audiences', type=d.T.array)]),
            withAudiencesMixin(audiences): { spec+: { provider+: { auth+: { kubernetes+: { serviceAccountRef+: { audiences+: if std.isArray(v=audiences) then audiences else [audiences] } } } } } },
            '#withName':: d.fn(help='"The name of the ServiceAccount resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { kubernetes+: { serviceAccountRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"Namespace of the resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { kubernetes+: { serviceAccountRef+: { namespace: namespace } } } } } },
          },
          '#withMountPath':: d.fn(help='"Path where the Kubernetes authentication backend is mounted in Vault, e.g:\\n\\"kubernetes\\', args=[d.arg(name='mountPath', type=d.T.string)]),
          withMountPath(mountPath): { spec+: { provider+: { auth+: { kubernetes+: { mountPath: mountPath } } } } },
          '#withRole':: d.fn(help='"A required field containing the Vault Role to assume. A Role binds a\\nKubernetes ServiceAccount with a set of Vault policies."', args=[d.arg(name='role', type=d.T.string)]),
          withRole(role): { spec+: { provider+: { auth+: { kubernetes+: { role: role } } } } },
        },
        '#ldap':: d.obj(help='"Ldap authenticates with Vault by passing username/password pair using\\nthe LDAP authentication method"'),
        ldap: {
          '#secretRef':: d.obj(help='"SecretRef to a key in a Secret resource containing password for the LDAP\\nuser used to authenticate with Vault using the LDAP authentication\\nmethod"'),
          secretRef: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { ldap+: { secretRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { ldap+: { secretRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { ldap+: { secretRef+: { namespace: namespace } } } } } },
          },
          '#withPath':: d.fn(help='"Path where the LDAP authentication backend is mounted\\nin Vault, e.g: \\"ldap\\', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { spec+: { provider+: { auth+: { ldap+: { path: path } } } } },
          '#withUsername':: d.fn(help='"Username is an LDAP username used to authenticate using the LDAP Vault\\nauthentication method"', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { spec+: { provider+: { auth+: { ldap+: { username: username } } } } },
        },
        '#tokenSecretRef':: d.obj(help='"TokenSecretRef authenticates with Vault by presenting a token."'),
        tokenSecretRef: {
          '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { provider+: { auth+: { tokenSecretRef+: { key: key } } } } },
          '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { provider+: { auth+: { tokenSecretRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { provider+: { auth+: { tokenSecretRef+: { namespace: namespace } } } } },
        },
        '#userPass':: d.obj(help='"UserPass authenticates with Vault by passing username/password pair"'),
        userPass: {
          '#secretRef':: d.obj(help='"SecretRef to a key in a Secret resource containing password for the\\nuser used to authenticate with Vault using the UserPass authentication\\nmethod"'),
          secretRef: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { userPass+: { secretRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { userPass+: { secretRef+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { userPass+: { secretRef+: { namespace: namespace } } } } } },
          },
          '#withPath':: d.fn(help='"Path where the UserPassword authentication backend is mounted\\nin Vault, e.g: \\"userpass\\', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { spec+: { provider+: { auth+: { userPass+: { path: path } } } } },
          '#withUsername':: d.fn(help='"Username is a username used to authenticate using the UserPass Vault\\nauthentication method"', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { spec+: { provider+: { auth+: { userPass+: { username: username } } } } },
        },
        '#withNamespace':: d.fn(help='"Name of the vault namespace to authenticate to. This can be different than the namespace your secret is in.\\nNamespaces is a set of features within Vault Enterprise that allows\\nVault environments to support Secure Multi-tenancy. e.g: \\"ns1\\".\\nMore about namespaces can be found here https://www.vaultproject.io/docs/enterprise/namespaces\\nThis will default to Vault.Namespace field if set, or empty otherwise"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { provider+: { auth+: { namespace: namespace } } } },
      },
      '#caProvider':: d.obj(help='"The provider for the CA bundle to use to validate Vault server certificate."'),
      caProvider: {
        '#withKey':: d.fn(help='"The key where the CA certificate can be found in the Secret or ConfigMap."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { provider+: { caProvider+: { key: key } } } },
        '#withName':: d.fn(help='"The name of the object located at the provider type."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { provider+: { caProvider+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The namespace the Provider type is in.\\nCan only be defined when used in a ClusterSecretStore."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { provider+: { caProvider+: { namespace: namespace } } } },
        '#withType':: d.fn(help='"The type of provider to use such as \\"Secret\\", or \\"ConfigMap\\"."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { provider+: { caProvider+: { type: type } } } },
      },
      '#tls':: d.obj(help="\"The configuration used for client side related TLS communication, when the Vault server\\nrequires mutual authentication. Only used if the Server URL is using HTTPS protocol.\\nThis parameter is ignored for plain HTTP protocol connection.\\nIt's worth noting this configuration is different from the \\\"TLS certificates auth method\\\",\\nwhich is available under the `auth.cert` section.\""),
      tls: {
        '#certSecretRef':: d.obj(help="\"CertSecretRef is a certificate added to the transport layer\\nwhen communicating with the Vault server.\\nIf no key for the Secret is specified, external-secret will default to 'tls.crt'.\""),
        certSecretRef: {
          '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { provider+: { tls+: { certSecretRef+: { key: key } } } } },
          '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { provider+: { tls+: { certSecretRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { provider+: { tls+: { certSecretRef+: { namespace: namespace } } } } },
        },
        '#keySecretRef':: d.obj(help="\"KeySecretRef to a key in a Secret resource containing client private key\\nadded to the transport layer when communicating with the Vault server.\\nIf no key for the Secret is specified, external-secret will default to 'tls.key'.\""),
        keySecretRef: {
          '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { provider+: { tls+: { keySecretRef+: { key: key } } } } },
          '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { provider+: { tls+: { keySecretRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { provider+: { tls+: { keySecretRef+: { namespace: namespace } } } } },
        },
      },
      '#withCaBundle':: d.fn(help='"PEM encoded CA bundle used to validate Vault server certificate. Only used\\nif the Server URL is using HTTPS protocol. This parameter is ignored for\\nplain HTTP protocol connection. If not set the system root certificates\\nare used to validate the TLS connection."', args=[d.arg(name='caBundle', type=d.T.string)]),
      withCaBundle(caBundle): { spec+: { provider+: { caBundle: caBundle } } },
      '#withForwardInconsistent':: d.fn(help='"ForwardInconsistent tells Vault to forward read-after-write requests to the Vault\\nleader instead of simply retrying within a loop. This can increase performance if\\nthe option is enabled serverside.\\nhttps://www.vaultproject.io/docs/configuration/replication#allow_forwarding_via_header"', args=[d.arg(name='forwardInconsistent', type=d.T.boolean)]),
      withForwardInconsistent(forwardInconsistent): { spec+: { provider+: { forwardInconsistent: forwardInconsistent } } },
      '#withHeaders':: d.fn(help='"Headers to be added in Vault request"', args=[d.arg(name='headers', type=d.T.object)]),
      withHeaders(headers): { spec+: { provider+: { headers: headers } } },
      '#withHeadersMixin':: d.fn(help='"Headers to be added in Vault request"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headers', type=d.T.object)]),
      withHeadersMixin(headers): { spec+: { provider+: { headers+: headers } } },
      '#withNamespace':: d.fn(help='"Name of the vault namespace. Namespaces is a set of features within Vault Enterprise that allows\\nVault environments to support Secure Multi-tenancy. e.g: \\"ns1\\".\\nMore about namespaces can be found here https://www.vaultproject.io/docs/enterprise/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { provider+: { namespace: namespace } } },
      '#withPath':: d.fn(help='"Path is the mount path of the Vault KV backend endpoint, e.g:\\n\\"secret\\". The v2 KV secret engine version specific \\"/data\\" path suffix\\nfor fetching secrets from Vault is optional and will be appended\\nif not present in specified path."', args=[d.arg(name='path', type=d.T.string)]),
      withPath(path): { spec+: { provider+: { path: path } } },
      '#withReadYourWrites':: d.fn(help='"ReadYourWrites ensures isolated read-after-write semantics by\\nproviding discovered cluster replication states in each request.\\nMore information about eventual consistency in Vault can be found here\\nhttps://www.vaultproject.io/docs/enterprise/consistency"', args=[d.arg(name='readYourWrites', type=d.T.boolean)]),
      withReadYourWrites(readYourWrites): { spec+: { provider+: { readYourWrites: readYourWrites } } },
      '#withServer':: d.fn(help='"Server is the connection address for the Vault server, e.g: \\"https://vault.example.com:8200\\"."', args=[d.arg(name='server', type=d.T.string)]),
      withServer(server): { spec+: { provider+: { server: server } } },
      '#withVersion':: d.fn(help='"Version is the Vault KV secret engine version. This can be either \\"v1\\" or\\n\\"v2\\". Version defaults to \\"v2\\"."', args=[d.arg(name='version', type=d.T.string)]),
      withVersion(version): { spec+: { provider+: { version: version } } },
    },
    '#retrySettings':: d.obj(help='"Used to configure http retries if failed"'),
    retrySettings: {
      '#withMaxRetries':: d.fn(help='', args=[d.arg(name='maxRetries', type=d.T.integer)]),
      withMaxRetries(maxRetries): { spec+: { retrySettings+: { maxRetries: maxRetries } } },
      '#withRetryInterval':: d.fn(help='', args=[d.arg(name='retryInterval', type=d.T.string)]),
      withRetryInterval(retryInterval): { spec+: { retrySettings+: { retryInterval: retryInterval } } },
    },
    '#withAllowEmptyResponse':: d.fn(help='"Do not fail if no secrets are found. Useful for requests where no data is expected."', args=[d.arg(name='allowEmptyResponse', type=d.T.boolean)]),
    withAllowEmptyResponse(allowEmptyResponse): { spec+: { allowEmptyResponse: allowEmptyResponse } },
    '#withController':: d.fn(help='"Used to select the correct ESO controller (think: ingress.ingressClassName)\\nThe ESO controller is instantiated with a specific controller name and filters VDS based on this property"', args=[d.arg(name='controller', type=d.T.string)]),
    withController(controller): { spec+: { controller: controller } },
    '#withMethod':: d.fn(help='"Vault API method to use (GET/POST/other)"', args=[d.arg(name='method', type=d.T.string)]),
    withMethod(method): { spec+: { method: method } },
    '#withParameters':: d.fn(help='"Parameters to pass to Vault write (for non-GET methods)"', args=[d.arg(name='parameters', type=d.T.any)]),
    withParameters(parameters): { spec+: { parameters: parameters } },
    '#withPath':: d.fn(help='"Vault path to obtain the dynamic secret from"', args=[d.arg(name='path', type=d.T.string)]),
    withPath(path): { spec+: { path: path } },
    '#withResultType':: d.fn(help='"Result type defines which data is returned from the generator.\\nBy default it is the \\"data\\" section of the Vault API response.\\nWhen using e.g. /auth/token/create the \\"data\\" section is empty but\\nthe \\"auth\\" section contains the generated token.\\nPlease refer to the vault docs regarding the result data structure.\\nAdditionally, accessing the raw response is possibly by using \\"Raw\\" result type."', args=[d.arg(name='resultType', type=d.T.string)]),
    withResultType(resultType): { spec+: { resultType: resultType } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
